
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVI = 5;
  public static final int SUMA = 2;
  public static final int MULT = 4;
  public static final int EOF = 0;
  public static final int PUNTCOMA = 8;
  public static final int NUMERO = 11;
  public static final int PARI = 6;
  public static final int ID = 10;
  public static final int IGUAL = 9;
  public static final int error = 1;
  public static final int PARD = 7;
  public static final int RESTA = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SUMA",
  "RESTA",
  "MULT",
  "DIVI",
  "PARI",
  "PARD",
  "PUNTCOMA",
  "IGUAL",
  "ID",
  "NUMERO"
  };
}

